services:
  # Background Worker (Telegram Bot)
  - type: worker
    name: madrid-bot-worker
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m backend.bot
    envVars:
      - key: BOT_TOKEN
        sync: false        # token-ը շարունակում ես դնել Environment-ում
      - key: DATABASE_URL
        sync: false        # վերցվում է հենց Environment-ից, ոչ թե fromDatabase
