services:
  - type: web
    name: madrid-telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m backend.bot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: DIGEST_INTERVAL
        value: "30"
      - key: SCHEDULER_TYPE
        value: "interval"
      - key: PYTHON_VERSION
        value: "3.11.9"
